# Generated by Django 6.0.4 on 2026-04-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[("full time", "full time"), ("part time", "part time")],
                default="full time",
                max_length=15,
            ),
        ),
    ]
