# Generated by Django 6.0.4 on 2026-04-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_job_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[("full time", "full time"), ("part time", "part time")],
                max_length=15,
            ),
        ),
    ]
