# Generated by Django 6.0.4 on 2026-04-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_alter_job_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="describtion",
            field=models.TextField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
