# Generated by Django 6.0.4 on 2026-04-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_job_describtion"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="job",
            name="published_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="vacancy",
            field=models.IntegerField(default=1),
        ),
    ]
