# Generated by Django 6.0.4 on 2026-04-11 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="Category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="job.category",
            ),
            preserve_default=False,
        ),
    ]
